/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterFace;

import Entity.Classify;
import Entity.Unit;
import Utils.DatabaseUtil;
import com.microsoft.sqlserver.jdbc.StringUtils;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.time.LocalDateTime;
import java.util.Locale;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Admin
 */
public class PayDialog extends javax.swing.JDialog {

    private Detail detail;
    private Connection conn = null;
    private PreparedStatement pst = null;
    private ResultSet rs = null;
    String sql = "select * from products";
    String maKH = "";
    String maHd = "";
    String diaChi = "";
    String sdt = "";
    String tenKh = "";
    String noCu = "";
    static String user = "";
    boolean isPayed = false;
    NumberFormat moneyFormatter = NumberFormat.getInstance(new Locale("vi", "VN"));

    /**
     * Creates new form ProductDialog
     */
    public PayDialog(java.awt.Frame parent, boolean modal, String tongTienHd, String noCu, String tongThanhToan, String maKh, String tenKh, String maHD, String diaChi, String sdt, String user) {

        super(parent, "Chỉnh sửa", modal);
        initComponents();
        connection();
        txbTongTien.setText(tongTienHd);
        txbTongThanhToan.setText(tongThanhToan);
        txbNoCu.setText(noCu);
        txbKhachHang.setText(tenKh);
        txbKhachTra.setText("0");
        maKH = maKh;
        maHd = maHD;
        this.diaChi = diaChi;
        this.sdt = sdt;
        this.tenKh = tenKh;
        this.user = user;
        this.noCu = noCu;
        countMoney();
        setLocationRelativeTo(null);
    }

    private void connection() {
        try {
            conn = DatabaseUtil.getConnection();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txbKhachHang = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txbTongTien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txbTongThanhToan = new javax.swing.JTextField();
        txbKhachTra = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txbConLai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txbNoCu = new javax.swing.JTextField();
        btnUpdateDebt = new javax.swing.JButton();
        btnSave2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(new java.awt.Color(102, 102, 255));
        setLocation(new java.awt.Point(200, 300));

        txbKhachHang.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txbKhachHang.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel7.setText("Khách trả:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel5.setText("Tổng tiền:");

        txbTongTien.setEditable(false);
        txbTongTien.setBackground(new java.awt.Color(255, 255, 255));
        txbTongTien.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txbTongTienupdateTotal(evt);
            }
        });
        txbTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbTongTienActionPerformed(evt);
            }
        });
        txbTongTien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbTongTienKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel6.setText("Tổng thanh toán:");

        txbTongThanhToan.setEditable(false);
        txbTongThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        txbTongThanhToan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txbTongThanhToanupdateTotal(evt);
            }
        });
        txbTongThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbTongThanhToanActionPerformed(evt);
            }
        });
        txbTongThanhToan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbTongThanhToanKeyReleased(evt);
            }
        });

        txbKhachTra.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txbKhachTraupdateTotal(evt);
            }
        });
        txbKhachTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbKhachTraActionPerformed(evt);
            }
        });
        txbKhachTra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbKhachTraKeyReleased(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Exit mini.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.setToolTipText("");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Save.png"))); // NOI18N
        btnSave1.setText("Lưu");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel4.setText("Còn lại:");

        txbConLai.setEditable(false);
        txbConLai.setBackground(new java.awt.Color(255, 255, 255));
        txbConLai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbConLaiKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel8.setText("Khách hàng:");

        jButton1.setText("Trả đủ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel9.setText("Nợ cũ:");

        txbNoCu.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txbNoCuupdateTotal(evt);
            }
        });
        txbNoCu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbNoCuActionPerformed(evt);
            }
        });
        txbNoCu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txbNoCuKeyReleased(evt);
            }
        });

        btnUpdateDebt.setText("Cập nhật");
        btnUpdateDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDebtActionPerformed(evt);
            }
        });

        btnSave2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Refresh-icon.png"))); // NOI18N
        btnSave2.setText("Khôi phục");
        btnSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txbTongThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txbNoCu)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnUpdateDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txbTongTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(btnSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txbKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txbConLai, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbNoCu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateDebt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txbTongThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbKhachTra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txbConLai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String moneyDis(String money) {
        DecimalFormat formatter = new DecimalFormat("###,###,###");
        String price = formatter.format(Double.parseDouble(money));
        return price;
    }

    private BigDecimal convertToMoney(String money) {
        String text = money.replace(",", ""); // Remove existing commas
        if (text.isEmpty()) {
            return null;
        }
        try {
            BigDecimal number = BigDecimal.valueOf(Double.parseDouble(text));
            return number;
        } catch (NumberFormatException ex) {
            ex.printStackTrace();
        }
        return null;
    }

    private double convertedToNumbers(String s) {
        String number = "";
        String[] array = s.replace(",", " ").split("\\s");
        for (String i : array) {
            number = number.concat(i);
        }
        return Double.parseDouble(number);
    }

    private String checkNull() {
        String mess = "";
        if (txbNoCu.getText().isBlank() || txbNoCu.getText().isEmpty()) {
            mess = "Vui lòng nhập số tiền nợ cũ!";
        } else if (txbKhachTra.getText().isBlank() || txbKhachTra.getText().isEmpty()) {
            mess = "Vui lòng nhập số tiền khách trả!";
        }
        return mess;
    }

    private void countMoney() {
        if (StringUtils.isEmpty(checkNull()) == false) {
            JOptionPane.showMessageDialog(null, checkNull(), "Lỗi", JOptionPane.ERROR);
        } else {
            BigDecimal tongTien = convertToMoney(txbTongTien.getText());
            BigDecimal noCu = convertToMoney(txbNoCu.getText());
            BigDecimal tongTienTT = tongTien.add(noCu);
            BigDecimal khachTra = convertToMoney(txbKhachTra.getText());
            BigDecimal conLai = BigDecimal.ZERO;

            if (tongTienTT.compareTo(khachTra) > 0) {
                conLai = tongTienTT.subtract(khachTra);
            }

            txbTongThanhToan.setText(moneyDis(tongTienTT.toString()));
            txbConLai.setText(moneyDis(conLai.toString()));
        }
    }

    private void txbTongTienupdateTotal(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txbTongTienupdateTotal
        // TODO add your handling code here:
    }//GEN-LAST:event_txbTongTienupdateTotal

    private void txbTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbTongTienActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txbTongTienActionPerformed

    private void txbTongTienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbTongTienKeyReleased
//        String text = txbTongTien.getText().replaceAll("[^0-9]", "");
//        DecimalFormat decimalFormat = new DecimalFormat("#.###");
//        txbTongTien.setText(text);
//
//        if (text.equals("0") == false) {
//            txbTongThanhToan.setText("1");
//        }
//        String checkNull = checkNull();
//        if (StringUtils.isEmpty(checkNull)) {
//            try {
//                BigDecimal tongSoLuong = getTongSoLuong();
//                txbIntoMoney.setText(moneyDis(String.valueOf(convertToMoney(txbConLai.getText()).multiply(tongSoLuong))));
//                txbKhachTra.setText(decimalFormat.format(tongSoLuong));
//            } catch (NumberFormatException e) {
//                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, checkNull, "Error", JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_txbTongTienKeyReleased

    private void txbTongThanhToanupdateTotal(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txbTongThanhToanupdateTotal
        // TODO add your handling code here:
    }//GEN-LAST:event_txbTongThanhToanupdateTotal

    private void txbTongThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbTongThanhToanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbTongThanhToanActionPerformed

    private void txbTongThanhToanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbTongThanhToanKeyReleased
        DecimalFormat formatter = new DecimalFormat("###,###,###");

        if (txbTongThanhToan.getText().equals("")) {
            return;
        } else {
            txbTongThanhToan.setText(formatter.format(convertedToNumbers(txbTongThanhToan.getText())));
        }
    }//GEN-LAST:event_txbTongThanhToanKeyReleased

    private void txbKhachTraupdateTotal(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txbKhachTraupdateTotal
        // TODO add your handling code here:
    }//GEN-LAST:event_txbKhachTraupdateTotal

    private void txbKhachTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbKhachTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbKhachTraActionPerformed

    private void txbKhachTraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbKhachTraKeyReleased
        DecimalFormat formatter = new DecimalFormat("###,###,###");

        if (txbKhachTra.getText().equals("")) {
            return;
        } else {
            txbKhachTra.setText(formatter.format(convertedToNumbers(txbKhachTra.getText())));
        }

        countMoney();
    }//GEN-LAST:event_txbKhachTraKeyReleased

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        String sqlChange = "UPDATE Orders SET TotalMoneyBill=?, OldDebt =?, TotalMoneyOrder =?,PayMoney=?, DebtBack =?, isPayed =?, CustomerID = ?, Customer = ?, Address =?, Phone = ?  WHERE ID='" + maHd + "'";
        String sqlUpdateDebt = "UPDATE Customer SET Debt=? WHERE ID='" + maKH + "'";
        try {
            pst = conn.prepareStatement(sqlChange);
            pst.setBigDecimal(1, convertToMoney(txbTongTien.getText()));
            pst.setBigDecimal(2, convertToMoney(txbNoCu.getText()));
            pst.setBigDecimal(3, convertToMoney(txbTongThanhToan.getText()));
            pst.setBigDecimal(4, convertToMoney(txbKhachTra.getText()));
            pst.setBigDecimal(5, convertToMoney(txbConLai.getText()));
            pst.setBoolean(6, true);
            pst.setString(7, maKH);
            pst.setString(8, tenKh);
            pst.setString(9, diaChi);
            pst.setString(10, sdt);

            pst.executeUpdate();

            pst = conn.prepareStatement(sqlUpdateDebt);
            pst.setBigDecimal(1, convertToMoney(txbConLai.getText()));
            pst.executeUpdate();
            isPayed = true;
            this.dispose();
            JOptionPane.showMessageDialog(null, "Lưu thay đổi thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSave1ActionPerformed

    public boolean isPayed() {
        return isPayed;
    }

    public String getNoCu() {
        return txbNoCu.getText();
    }

    public String getKhachTra() {
        return txbKhachTra.getText();
    }

    public String getConLai() {
        return txbConLai.getText();
    }

    public String getTong() {
        return txbTongThanhToan.getText();
    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txbConLaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbConLaiKeyReleased

    }//GEN-LAST:event_txbConLaiKeyReleased

    private void txbNoCuupdateTotal(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txbNoCuupdateTotal
        // TODO add your handling code here:
    }//GEN-LAST:event_txbNoCuupdateTotal

    private void txbNoCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbNoCuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbNoCuActionPerformed

    private void txbNoCuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbNoCuKeyReleased
        DecimalFormat formatter = new DecimalFormat("###,###,###");

        if (txbNoCu.getText().equals("")) {
            return;
        } else {
            txbNoCu.setText(formatter.format(convertedToNumbers(txbNoCu.getText())));
        }

        countMoney();
    }//GEN-LAST:event_txbNoCuKeyReleased

    private void btnUpdateDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDebtActionPerformed
        boolean checkLogin = showPasswordDialog();
        if (checkLogin) {
            int Click = JOptionPane.showConfirmDialog(null, "Bạn có muốn cập nhật nợ cũ cho khách hàng này không?", "Thông Báo", 2);
            if (Click == JOptionPane.YES_OPTION) {
                String sqlChange = "UPDATE Customer SET Debt=?, OldDebt=? WHERE ID='" + maKH + "'";
                try {
                    pst = conn.prepareStatement(sqlChange);
                    pst.setBigDecimal(1, convertToMoney(txbNoCu.getText()));
                    pst.setBigDecimal(2, convertToMoney(txbNoCu.getText()));

                    pst.executeUpdate();
                    countMoney();
                    JOptionPane.showMessageDialog(null, "Cập nhật nợ cũ thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnUpdateDebtActionPerformed

    private static boolean showPasswordDialog() {
        CheckAdminDialog dialog = new CheckAdminDialog(new javax.swing.JFrame(), true, user);
        dialog.setVisible(true);
        return dialog.isCheckLogin();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txbKhachTra.setText(txbTongThanhToan.getText());
        countMoney();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave2ActionPerformed
        txbNoCu.setText(noCu);
        countMoney();
    }//GEN-LAST:event_btnSave2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PayDialog dialog = new PayDialog(new javax.swing.JFrame(), true, null, null, null, null, null, null, null, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnSave2;
    private javax.swing.JButton btnUpdateDebt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txbConLai;
    private javax.swing.JLabel txbKhachHang;
    private javax.swing.JTextField txbKhachTra;
    private javax.swing.JTextField txbNoCu;
    private javax.swing.JTextField txbTongThanhToan;
    private javax.swing.JTextField txbTongTien;
    // End of variables declaration//GEN-END:variables
}
